services:
  - type: static
    name: sevennax7na-system
    runtime: static
    buildCommand: null
    staticPublishPath: .
    routes:
      - type: rewrite
        source: /(.*)
        destination: /index.html
