services:
  - type: web
    name: 7nax7na-website
    runtime: static
    buildCommand: ""
    staticPublishPath: .
    routes:
      - type: rewrite
        source: /(.*)
        destination: /$1
      - type: rewrite
        source: /
        destination: /index.html
